### ISSUE TITLE
Problem to get dataset

### ISSUE THREAD

**Issue by butarr** [datasciencebr/whistleblower#21]
I was setting up my env and then I had a problem to execute this command:
`docker-compose run worker python whistleblower/get_dataset.py`

Output:
```
Starting whistleblower_mongo_1 ... done
Starting whistleblower_rabbitmq_1 ... done
Traceback (most recent call last):
  File "whistleblower/get_dataset.py", line 252, in <module>
    fetch()
  File "whistleblower/get_dataset.py", line 134, in fetch
    urlretrieve(url, zip_file_path)
  File "/usr/local/lib/python3.6/urllib/request.py", line 258, in urlretrieve
    tfp = open(filename, 'wb')
PermissionError: [Errno 13] Permission denied: 'data/Ano-2015.zip'
```

[Looks like](https://stackoverflow.com/questions/39794793/docker-volume-option-create-folder-as-root-user) this is a expected Docker's behavior, when its run and uses a volume that is not there, it will creates as root :/ 

Well... this was enough to me:
`mkdir -p data && docker-compose run worker python whistleblower/get_dataset.py`

**Comment by cuducos** [comment]
As the script path `./whistleblower/get_database.py` and `./data/` volume is at the root directory does it make sense to have `../data/Ano-2015.zip` instead of `data/Ano-2015.zip` in the script?

**Comment by cuducos** [comment]
Closed by inactivity.
