### ISSUE TITLE
Adds Coverage monitoring

### ISSUE THREAD

**Issue by lipemorais** [datasciencebr/whistleblower#9]
**What is the purpose of this Issue?**
The purpose of this issue is include Continuous Integration for the project.

**What could be done to achieve this purpose?**
Adds a coverage tool like [coveralls](coveralls.io) as some other repositories will help to improve the code quality and maintainability.

**Comment by lipemorais** [comment]
It's already done.

**Comment by cuducos** [comment]
I think this Issue, taking it title, still valid: coverage and quality checks are welcomed. Just update the opening post at _What could be done to achieve this purpose?_ ; )
